/**
 * Descripciones con forma real y su categoría correcta, para medir la
 * precisión del clasificador sin sacar datos del teléfono. Incluye comercios
 * del catálogo (que el catálogo ya resuelve) y comercios de barrio (que solo
 * el aprendizaje resuelve), con variantes de sucursal.
 */
export const LABELED_SAMPLE: readonly { descripcion: string; slug: string }[] = [
  { descripcion: 'COMPRA PANADERIA DONA ROSA', slug: 'antojos' },
  { descripcion: 'COMPRA PANADERIA DONA ROSA SUR', slug: 'antojos' },
  { descripcion: 'PAGO EN PANADERIA DONA ROSA CALLE 80', slug: 'antojos' },
  { descripcion: 'COMPRA RESTAURANTE EL PAISA', slug: 'restaurantes' },
  { descripcion: 'PAGO EN RESTAURANTE EL PAISA NORTE', slug: 'restaurantes' },
  { descripcion: 'COMPRA RESTAURANTE EL PAISA 2', slug: 'restaurantes' },
  { descripcion: 'COMPRA FERRETERIA LA 45', slug: 'hogar' },
  { descripcion: 'COMPRA FERRETERIA LA 45 SUR', slug: 'hogar' },
  { descripcion: 'COMPRA DROGUERIA SAN JOSE', slug: 'drogueria' },
  { descripcion: 'COMPRA DROGUERIA SAN JOSE CENTRO', slug: 'drogueria' },
  { descripcion: 'COMPRA PAPELERIA CENTRAL', slug: 'educacion' },
  { descripcion: 'COMPRA PAPELERIA CENTRAL 2', slug: 'educacion' },
  { descripcion: 'PAGO EN PARQUEADERO CENTRAL', slug: 'parqueadero-y-peajes' },
  { descripcion: 'PAGO EN PARQUEADERO CENTRAL NORTE', slug: 'parqueadero-y-peajes' },
  { descripcion: 'COMPRA TIENDA LA ESQUINA', slug: 'mercado' },
  { descripcion: 'COMPRA TIENDA LA ESQUINA SUR', slug: 'mercado' },
  { descripcion: 'COMPRA LAVANDERIA EXPRESS', slug: 'hogar' },
  { descripcion: 'COMPRA LAVANDERIA EXPRESS CALLE 100', slug: 'hogar' },
  { descripcion: 'COMPRA VETERINARIA HUELLITAS', slug: 'mascotas' },
  { descripcion: 'PAGO EN VETERINARIA HUELLITAS SUR', slug: 'mascotas' },
  { descripcion: 'COMPRA PELUQUERIA DONDE MARY', slug: 'cuidado-personal' },
  { descripcion: 'PAGO EN PELUQUERIA DONDE MARY 2', slug: 'cuidado-personal' },
  { descripcion: 'TRANSFERENCIA A MAMA', slug: 'apoyo-familiar' },
  { descripcion: 'TRANSFERENCIA A MAMA CELULAR', slug: 'apoyo-familiar' },
  { descripcion: 'PAGO PSE CONJUNTO LOS ALAMOS', slug: 'administracion' },
  { descripcion: 'PAGO PSE CONJUNTO LOS ALAMOS ADMON', slug: 'administracion' },
  { descripcion: 'PAGO PSE ARRIENDO APTO 302', slug: 'arriendo' },
  { descripcion: 'PAGO PSE ARRIENDO APTO 302 SEPTIEMBRE', slug: 'arriendo' },
  { descripcion: 'COMPRA GIMNASIO FUERZA TOTAL', slug: 'gimnasio-y-deporte' },
  { descripcion: 'PAGO EN GIMNASIO FUERZA TOTAL 2', slug: 'gimnasio-y-deporte' },
  { descripcion: 'COMPRA LIBRERIA NACIONAL', slug: 'educacion' },
  { descripcion: 'COMPRA LIBRERIA NACIONAL SUR', slug: 'educacion' },
  { descripcion: 'COMPRA CARNICERIA EL BUEN CORTE', slug: 'mercado' },
  { descripcion: 'COMPRA CARNICERIA EL BUEN CORTE 2', slug: 'mercado' },
  { descripcion: 'COMPRA FRUVER LA COSECHA', slug: 'mercado' },
  { descripcion: 'COMPRA FRUVER LA COSECHA NORTE', slug: 'mercado' },
  { descripcion: 'COMPRA BAR LA TERRAZA', slug: 'salidas' },
  { descripcion: 'PAGO EN BAR LA TERRAZA CENTRO', slug: 'salidas' },
  { descripcion: 'COMPRA ODONTOLOGIA SONRISAS', slug: 'salud' },
  { descripcion: 'PAGO EN ODONTOLOGIA SONRISAS 2', slug: 'salud' },
  // Del catálogo, para comprobar que el aprendizaje no lo contradice sin motivo.
  { descripcion: 'COMPRA EXITO SUR', slug: 'mercado' },
  { descripcion: 'COMPRA EXITO CALLE 80', slug: 'mercado' },
  { descripcion: 'PAGO EN RAPPI', slug: 'domicilios' },
  { descripcion: 'COMPRA RAPPI*RAPPI PRO', slug: 'domicilios' },
  { descripcion: 'COMPRA UBER *TRIP', slug: 'taxi-y-apps' },
  { descripcion: 'COMPRA UBER *TRIP HELP.UBER.COM', slug: 'taxi-y-apps' },
  { descripcion: 'COMPRA NETFLIX.COM', slug: 'suscripciones' },
  { descripcion: 'COMPRA SPOTIFY', slug: 'suscripciones' },
  { descripcion: 'IMPTO GOBIERNO 4X1000', slug: 'cuatro-por-mil' },
  { descripcion: 'CUOTA DE MANEJO', slug: 'comisiones-bancarias' },
];
