/**
 * Descripciones con la forma real de Bancolombia (hallazgos del sprint 01):
 * tipo en mayúsculas, a veces «PSE», a veces terminal «*NNNN», comercio, y a
 * veces ciudad o sucursal. Los comercios son reales; los montos no importan.
 *
 * Sirve para medir cobertura del catálogo sin sacar datos del teléfono. Cuando
 * el guion `cobertura-comercios` encuentre claves desconocidas frecuentes en
 * la base real, se añaden aquí y al catálogo.
 */
export const SAMPLE_DESCRIPTIONS: readonly string[] = [
  'COMPRA PSE *4471 EXITO SUR',
  'COMPRA EXITO CALLE 80',
  'ALMACENES EXITO SA',
  'COMPRA CARULLA 85',
  'COMPRA TIENDAS D1 SAS',
  'COMPRA ARA MEDELLIN',
  'COMPRA JUMBO',
  'PAGO EN RAPPI',
  'COMPRA RAPPI*RAPPI PRO',
  'COMPRA DIDI FOOD',
  'COMPRA UBER *TRIP HELP.UBER.COM',
  'COMPRA DIDI',
  'COMPRA CABIFY',
  'COMPRA TERPEL LA 30',
  'COMPRA NETFLIX.COM',
  'COMPRA SPOTIFY',
  'COMPRA GOOGLE *YOUTUBE',
  'COMPRA DISNEY PLUS',
  'COMPRA APPLE.COM/BILL',
  'PAGO PSE CLARO MOVIL',
  'PAGO PSE TIGO',
  'PAGO PSE EPM',
  'PAGO PSE ENEL CODENSA',
  'PAGO PSE VANTI',
  'PAGO PSE ACUEDUCTO',
  'COMPRA FARMATODO',
  'COMPRA CRUZ VERDE',
  'COMPRA LA REBAJA',
  'COMPRA SMART FIT',
  'COMPRA HOMECENTER',
  'COMPRA FALABELLA',
  'COMPRA ZARA',
  'COMPRA MERCADOLIBRE',
  'COMPRA AMAZON',
  'COMPRA CINE COLOMBIA',
  'COMPRA STEAM',
  'COMPRA AVIANCA',
  'COMPRA AIRBNB',
  'COMPRA JUAN VALDEZ',
  'COMPRA CREPES Y WAFFLES',
  'COMPRA FRISBY',
  'COMPRA MC DONALDS',
  'COMPRA OXXO',
  'IMPTO GOBIERNO 4X1000',
  'CUOTA DE MANEJO',
  'IVA COMISION',
  'TRANSFERENCIA A NEQUI',
  'TRANSFERENCIA DE NEQUI',
  'RETIRO CAJERO',
  'RETIRO EN CORRESPONSAL',
  'ABONO NOMINA',
  // Sin catálogo, a propósito: comercios de barrio.
  'COMPRA PANADERIA DONA ROSA',
  'PAGO EN RESTAURANTE EL PAISA',
  'COMPRA FERRETERIA LA 45',
  'COMPRA DROGUERIA SAN JOSE',
  'COMPRA PAPELERIA CENTRAL',
  'PAGO EN PARQUEADERO CENTRAL',
  'COMPRA TIENDA LA ESQUINA',
  'COMPRA LAVANDERIA EXPRESS',
  'COMPRA VETERINARIA HUELLITAS',
];
